/* hostrules.js: the `_headers` and `_redirects` files for a static host that reads the Cloudflare Pages format,
   and the code that reads them back. build.js writes the files with the first two functions; tools/serve.js and
   tests/host.test.js read them with the rest, so what is tested is the real file.

   Format (https://developers.cloudflare.com/pages/configuration/headers/ and .../redirects/):
     _headers    a URL pattern on its own line, then indented "Name: value" lines. When several rules match one URL,
                 the host JOINS repeated header names with a comma, so no header may be set by two rules here.
     _redirects  "from to status" per line, first match wins, status defaults to 302 (so every rule says 301).
   In patterns, * matches anything (once per pattern, available as :splat) and :name matches one path segment. */
'use strict';

/* What the site really uses, and nothing else:
   script-src 'self'   its own bundle (no inline scripts: the JSON-LD and page-data blocks are data, not scripts)
   style-src 'self'    its own stylesheets (the app only sets styles through the style API, which a policy allows)
   font-src 'self'     its own woff2 files
   img-src 'self'      icons, favicon
   manifest-src 'self' site.webmanifest
   worker-src blob:    the Web Worker that parses large input is built from a blob: URL
   Everything else (connections, frames, objects, media) falls back to default-src 'none'. */
const CSP = ["default-src 'none'", "script-src 'self'", "style-src 'self'", "font-src 'self'", "img-src 'self'", "manifest-src 'self'",
  "worker-src blob:", "base-uri 'none'", "form-action 'none'", "frame-ancestors 'none'"].join('; ');
/* features this site never uses, switched off. Clipboard access is left alone: the copy and share buttons need it. */
const PERMISSIONS = ['accelerometer', 'bluetooth', 'camera', 'display-capture', 'geolocation', 'gyroscope', 'hid', 'magnetometer',
  'microphone', 'midi', 'payment', 'serial', 'usb', 'xr-spatial-tracking'].map(f => f + '=()').join(', ');

const CACHE = {
  asset: 'public, max-age=31536000, immutable',          /* the file name carries a hash of its content */
  html: 'public, max-age=0, must-revalidate',            /* always asked again, answered with a tiny 304 when unchanged */
  file: 'public, max-age=3600, must-revalidate',         /* robots.txt, sitemap.xml, the manifest: at most an hour old */
};

/* `slugs` are the page folders, "" being the home page. Each page gets its own exact rule: one broad pattern for
   every address ending in a slash would also match /assets/fonts/ and set Cache-Control twice. */
function headersFile(slugs) {
  const rule = (pattern, ...lines) => pattern + '\n' + lines.map(l => '  ' + l).join('\n');
  return [
    '# Generated by build.js. Read by Cloudflare Pages, and by tools/serve.js for local testing.\n' +
    '# Cloudflare joins a header with the same name from several matching rules, so each header below is set by exactly one rule.',
    rule('/*', 'Content-Security-Policy: ' + CSP, 'X-Content-Type-Options: nosniff', 'Referrer-Policy: strict-origin-when-cross-origin', 'Permissions-Policy: ' + PERMISSIONS),
    rule('/assets/*', 'Cache-Control: ' + CACHE.asset),
    ...slugs.map(s => rule(s ? '/' + s + '/' : '/', 'Cache-Control: ' + CACHE.html)),
    rule('/404.html', 'Cache-Control: ' + CACHE.html),
    rule('/robots.txt', 'Cache-Control: ' + CACHE.file),
    rule('/sitemap.xml', 'Cache-Control: ' + CACHE.file),
    rule('/site.webmanifest', 'Cache-Control: ' + CACHE.file),
  ].join('\n\n') + '\n';
}

/* One canonical form: lowercase, with a trailing slash. Every rule goes straight to its final address. */
function redirectsFile(slugs) {
  const rows = [['/index.html', '/']];
  for (const s of slugs.filter(Boolean)) rows.push(['/' + s, '/' + s + '/'], ['/' + s + '/index.html', '/' + s + '/']);
  const w = Math.max(...rows.map(r => r[0].length)) + 2;
  return '# Generated by build.js. Only the lowercase form with a trailing slash is served; these send the other spellings there in one step.\n' +
    '# Status is spelled out because the default would be 302.\n\n' + rows.map(([a, b]) => a.padEnd(w) + b + '  301').join('\n') + '\n';
}

/* ---------- reading the files ---------- */
const lines = text => text.split(/\r?\n/).map(l => l.replace(/\s+$/, '')).filter(l => l && !l.trimStart().startsWith('#'));

function parseHeaders(text) {
  const rules = [];
  for (const l of lines(text)) {
    if (!/^\s/.test(l)) { rules.push({ pattern: l, set: [], remove: [] }); continue; }
    const cur = rules[rules.length - 1], t = l.trim();
    if (!cur) throw new Error('_headers: a header line comes before any URL pattern: ' + t);
    if (t.startsWith('! ')) cur.remove.push(t.slice(2).trim());
    else { const i = t.indexOf(':'); if (i < 1) throw new Error('_headers: not a "Name: value" line: ' + t); cur.set.push([t.slice(0, i).trim(), t.slice(i + 1).trim()]); }
  }
  return rules;
}
function parseRedirects(text) {
  return lines(text).map(l => {
    const [from, to, code] = l.trim().split(/\s+/);
    if (!from || !to) throw new Error('_redirects: needs a source and a destination: ' + l);
    return { from, to, status: code ? +code : 302 };
  });
}

/* A pattern as a regular expression. Matching is case sensitive, like the paths on the host. */
function compile(pattern) {
  let re = '';
  const names = [];
  for (let i = 0; i < pattern.length;) {
    const c = pattern[i], m = c === ':' ? /^:([A-Za-z]\w*)/.exec(pattern.slice(i)) : null;
    if (c === '*') { re += '(.*)'; names.push('splat'); i++; }
    else if (m) { re += '([^/]+)'; names.push(m[1]); i += m[0].length; }
    else { re += c.replace(/[.+?^${}()|[\]\\\/-]/g, '\\$&'); i++; }
  }
  return { re: new RegExp('^' + re + '$'), names };
}
function match(pattern, pathname) {
  const { re, names } = compile(pattern), m = re.exec(pathname);
  if (!m) return null;
  const out = {};
  names.forEach((n, i) => { out[n] = m[i + 1]; });
  return out;
}

/* The headers a request for `pathname` gets, and any header name that two matching rules both set. */
function headersFor(rules, pathname) {
  const got = new Map(), repeated = new Set();
  for (const r of rules) {
    if (!match(r.pattern, pathname)) continue;
    for (const n of r.remove) got.delete(n.toLowerCase());
    for (const [n, v] of r.set) {
      const k = n.toLowerCase();
      if (got.has(k)) { repeated.add(n); got.get(k).value += ', ' + v; } else got.set(k, { name: n, value: v });
    }
  }
  return { headers: Object.fromEntries([...got.values()].map(h => [h.name, h.value])), repeated: [...repeated] };
}
function redirectFor(rules, pathname) {
  for (const r of rules) {
    const p = match(r.from, pathname);
    if (p) return { status: r.status, to: r.to.replace(/:([A-Za-z]\w*)/g, (m, n) => (n in p ? p[n] : m)) };
  }
  return null;
}

module.exports = { CSP, PERMISSIONS, CACHE, headersFile, redirectsFile, parseHeaders, parseRedirects, match, headersFor, redirectFor };
